### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-js-eslint#2]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://craven-dad.surge.sh/) and meets the following [project](http://lansingcodelab.com/lessons/js-eslint/1) criteria:
- [x] [This HTML file](https://gist.github.com/chrisvfritz/934c7cef66c524c185fed50c5b3f47c1) is used as a base for the project
- [x] The project folder contains a properly configured `.eslintrc.js` file
- [x] All linting errors in the `script` tag are fixed (so no red dots appear in Atom)
- [x] Every feature of the todo app works correctly, with no errors ever appearing in the JavaScript console

**Comment by chrisvfritz** [comment]
Repo is empty. 😕

**Comment by KatieMFritz** [comment]
Okay, how about now?

**Comment by chrisvfritz** [comment]
:shipit:
